name: Problema na página
description: Ajude a melhorar o conteúdo ou qualidade de uma página do docs.flutterbrasil.dev
labels: [from.page-issue]
body:
  - type: markdown
    attributes:
      value: |
          Encontrou um erro de digitação? Você pode corrigir você mesmo!

          1. Clique no link _Ver código-fonte_ à esquerda do link _relatar um problema_ que você clicou
             para chegar neste formulário. O código-fonte da página do GitHub deve ser exibido.
          1. Clique no ícone de lápis exibido acima do código-fonte.
          1. Corrija o erro.
          1. Clique em **Commit changes...**.
          1. Atualize a mensagem de commit e adicione uma descrição.
          1. Clique em **Propose changes**.

          Se você quiser que outro colaborador corrija este problema, preencha este formulário.
  - type: input
    id: page-url
    attributes:
      label: URL da página
      placeholder: "Adicione o endereço desta página. Um exemplo seria https://docs.flutterbrasil.dev/guides"
    validations:
      required: true
  - type: input
    id: page-source
    attributes:
      label: Código-fonte da página
      placeholder: O link do problema fornece esta informação.
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Descreva o problema
      placeholder: Forneça uma descrição clara e concisa do que você acredita estar incorreto.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Correção esperada
      placeholder: Forneça uma descrição clara e concisa de como você acha que este problema deve ser corrigido.
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Contexto adicional
      placeholder: |
        Forneça qualquer outra informação que deva ser conhecida sobre o problema.
        Isso pode incluir:

        * quando no seu fluxo de trabalho isso ocorreu
        * qual plataforma e navegador você está usando
        * outras configurações ou informações circunstanciais que você acha
          que podem impactar a correção do seu problema
    validations:
      required: false
  - type: checkboxes
    id: volunteer
    attributes:
      label: Eu gostaria de corrigir este problema.
      description: Nos informe se você quer tentar corrigir isso você mesmo.
      options:
        - label: Vou tentar corrigir este problema no docs.flutterbrasil.dev.
          required: false
