name: animated_container
description: Sample code for cookbook.

environment:
  sdk: ^3.0.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
